import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./ApolloWraper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import { ApolloClient, InMemoryCache, ApolloProvider, gql } from "@apollo/client";

// const client = new ApolloClient({
//   uri: 'https://countries.trevorblades.com/graphql',
//   cache: new InMemoryCache(),
// });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ApolloWrapper><body>{children}</body></ApolloWrapper>
    </html>
  );
}
